// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Styles:
export const TOGGLE_NEON_THEME = 'TOGGLE_NEON_THEME';
export const ANIMATE_CLOUD_ICON = 'ANIMATE_CLOUD_ICON';
export const IGNORE_NAVBAR_SHORTCUTS = "IGNORE_NAVBAR_SHORTCUTS";

// Notes
export const UPDATE_NOTES = "UPDATE_NOTES";
export const SET_LAST_NOTES = "SET_LAST_NOTES";
export const CLEAR_STATE = "CLEAR_STATE";
export const SERVER_RESPONSE = "SERVER_RESPONSE";
export const SET_NOTE_ORIGIN = "SET_NOTE_ORIGIN";